-- Woodpecker: QR-linked, append-only task collaboration.
create table if not exists public.woodpecker_tasks (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  campaign_id bigint not null references public.qr_campaigns(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  description text,
  status text not null default 'open' check (status in ('open','completed')),
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create table if not exists public.woodpecker_task_history (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.woodpecker_tasks(id) on delete cascade,
  event_type text not null check (event_type in ('created','message','completed')),
  message text,
  actor_id uuid references auth.users(id),
  actor_name text,
  created_at timestamptz not null default now()
);
create index if not exists woodpecker_tasks_campaign_idx on public.woodpecker_tasks(campaign_id);
create index if not exists woodpecker_history_task_idx on public.woodpecker_task_history(task_id, created_at);
alter table public.woodpecker_tasks enable row level security;
alter table public.woodpecker_task_history enable row level security;
drop policy if exists "workspace members read woodpecker tasks" on public.woodpecker_tasks;
drop policy if exists "workspace managers create woodpecker tasks" on public.woodpecker_tasks;
drop policy if exists "public reads active campaign tasks" on public.woodpecker_tasks;
drop policy if exists "workspace members read task history" on public.woodpecker_task_history;
drop policy if exists "public reads active task history" on public.woodpecker_task_history;
create policy "workspace members read woodpecker tasks" on public.woodpecker_tasks for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "workspace managers create woodpecker tasks" on public.woodpecker_tasks for insert to authenticated with check (public.is_workspace_manager(workspace_id) and exists (select 1 from public.qr_campaigns c where c.id=campaign_id and c.workspace_id=workspace_id));
create policy "public reads active campaign tasks" on public.woodpecker_tasks for select to anon using (exists (select 1 from public.qr_campaigns c where c.id=campaign_id and c.is_active));
create policy "workspace members read task history" on public.woodpecker_task_history for select to authenticated using (exists (select 1 from public.woodpecker_tasks t where t.id=task_id and public.is_workspace_member(t.workspace_id)));
create policy "public reads active task history" on public.woodpecker_task_history for select to anon using (exists (select 1 from public.woodpecker_tasks t join public.qr_campaigns c on c.id=t.campaign_id where t.id=task_id and c.is_active));

create or replace function public.get_public_woodpecker_portal(target_token text)
returns table(id bigint, title text, description text, status text, history jsonb)
language sql stable security definer set search_path=public
as $$
  select t.id, t.title, t.description, t.status,
    coalesce((select jsonb_agg(h order by h.created_at) from (
      select id, event_type, message, actor_name, created_at from public.woodpecker_task_history where task_id=t.id
    ) h), '[]'::jsonb)
  from public.woodpecker_tasks t join public.qr_campaigns c on c.id=t.campaign_id
  where c.token=target_token and c.is_active order by t.created_at desc;
$$;

create or replace function public.add_woodpecker_message(target_task_id bigint, message_text text, actor_name text default 'QR visitor')
returns void language plpgsql security definer set search_path=public
as $$
begin
  if length(trim(message_text)) = 0 or length(message_text) > 2000 then raise exception 'Message must be between 1 and 2000 characters'; end if;
  if not exists (select 1 from public.woodpecker_tasks t join public.qr_campaigns c on c.id=t.campaign_id where t.id=target_task_id and c.is_active) then raise exception 'Task not found'; end if;
  insert into public.woodpecker_task_history(task_id,event_type,message,actor_name) values(target_task_id,'message',trim(message_text),left(trim(actor_name),100));
end; $$;

create or replace function public.complete_woodpecker_task(target_task_id bigint)
returns void language plpgsql security definer set search_path=public
as $$
begin
  if not exists (select 1 from public.woodpecker_tasks t join public.qr_campaigns c on c.id=t.campaign_id where t.id=target_task_id and c.is_active) then raise exception 'Task not found'; end if;
  update public.woodpecker_tasks set status='completed', completed_at=now() where id=target_task_id and status <> 'completed';
  if found then insert into public.woodpecker_task_history(task_id,event_type,message,actor_id) values(target_task_id,'completed','Task marked complete',auth.uid()); end if;
end; $$;

create or replace function public.log_woodpecker_task_created()
returns trigger language plpgsql security definer set search_path=public
as $$ begin insert into public.woodpecker_task_history(task_id,event_type,message,actor_id) values(new.id,'created',new.title,new.created_by); return new; end; $$;
drop trigger if exists woodpecker_task_created on public.woodpecker_tasks;
create trigger woodpecker_task_created after insert on public.woodpecker_tasks for each row execute function public.log_woodpecker_task_created();
grant execute on function public.get_public_woodpecker_portal(text) to anon, authenticated;
grant execute on function public.add_woodpecker_message(bigint,text,text) to anon, authenticated;
grant execute on function public.complete_woodpecker_task(bigint) to anon, authenticated;
do $$
begin
  begin
    alter publication supabase_realtime add table public.woodpecker_tasks;
  exception when duplicate_object then
    null;
  end;
  begin
    alter publication supabase_realtime add table public.woodpecker_task_history;
  exception when duplicate_object then
    null;
  end;
end;
$$;
