-- Answer-triggered email and external-review benefits.
-- Run after the existing 20260908 migrations.

alter table public.polls
  add column if not exists email_benefit_type text not null default 'none'
    check (email_benefit_type in ('none', 'voucher', 'discount_code')),
  add column if not exists email_benefit_value text,
  add column if not exists email_benefit_url text,
  add column if not exists review_platforms jsonb not null default '[]'::jsonb,
  add column if not exists review_trigger_answers text[] not null default '{}',
  add column if not exists review_benefit_type text not null default 'none'
    check (review_benefit_type in ('none', 'voucher', 'discount_code')),
  add column if not exists review_benefit_value text,
  add column if not exists review_benefit_url text;

create table if not exists public.review_benefit_claims (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  poll_id bigint not null references public.polls(id) on delete cascade,
  selected_answers text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  claim_token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create index if not exists idx_review_benefit_claims_workspace_status
  on public.review_benefit_claims(workspace_id, status, created_at desc);
create index if not exists idx_review_benefit_claims_token
  on public.review_benefit_claims(claim_token);

alter table public.review_benefit_claims enable row level security;

drop policy if exists "managers can view review benefit claims" on public.review_benefit_claims;
drop policy if exists "managers can review review benefit claims" on public.review_benefit_claims;
create policy "managers can view review benefit claims" on public.review_benefit_claims
for select to authenticated using (public.is_workspace_manager(workspace_id));
create policy "managers can review review benefit claims" on public.review_benefit_claims
for update to authenticated using (public.is_workspace_manager(workspace_id))
with check (public.is_workspace_manager(workspace_id));

create or replace function public.create_review_benefit_claim(
  target_poll_id bigint,
  selected_answers text[]
)
returns table(claim_token uuid, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_workspace_id uuid;
  target_triggers text[];
  new_token uuid;
begin
  select workspace_id, review_trigger_answers
    into target_workspace_id, target_triggers
  from public.polls
  where id = target_poll_id;

  if target_workspace_id is null then
    raise exception 'The poll does not exist.';
  end if;

  if coalesce(array_length(target_triggers, 1), 0) = 0
    or not exists (
      select 1 from unnest(coalesce(selected_answers, '{}')) answer
      where answer = any(target_triggers)
    ) then
    raise exception 'This vote is not eligible for an external review benefit.';
  end if;

  insert into public.review_benefit_claims (workspace_id, poll_id, selected_answers)
  values (target_workspace_id, target_poll_id, coalesce(selected_answers, '{}'))
  returning review_benefit_claims.claim_token into new_token;

  return query select new_token, 'pending'::text;
end;
$$;

grant execute on function public.create_review_benefit_claim(bigint, text[]) to anon, authenticated;

create or replace function public.get_public_review_benefit_claim(target_token uuid)
returns table(
  claim_token uuid,
  poll_id bigint,
  status text,
  review_platforms jsonb,
  benefit_type text,
  benefit_value text,
  benefit_url text
)
language sql
security definer
set search_path = public
stable
as $$
  select c.claim_token, c.poll_id, c.status, p.review_platforms,
    p.review_benefit_type, p.review_benefit_value, p.review_benefit_url
  from public.review_benefit_claims c
  join public.polls p on p.id = c.poll_id
  where c.claim_token = target_token;
$$;

grant execute on function public.get_public_review_benefit_claim(uuid) to anon, authenticated;

create or replace function public.review_review_benefit_claim(
  target_claim_id bigint,
  next_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_workspace_id uuid;
begin
  if next_status not in ('approved', 'rejected') then
    raise exception 'Invalid review claim status.';
  end if;

  select workspace_id into target_workspace_id
  from public.review_benefit_claims
  where id = target_claim_id;

  if target_workspace_id is null or not public.is_workspace_manager(target_workspace_id) then
    raise exception 'You do not have access to review this claim.';
  end if;

  update public.review_benefit_claims
  set status = next_status, reviewed_at = now(), reviewed_by = auth.uid()
  where id = target_claim_id;
end;
$$;

grant execute on function public.review_review_benefit_claim(bigint, text) to authenticated;
