-- Recurring/rotating polls: a QR campaign can rotate through an ordered list of polls automatically.
create table if not exists public.poll_rotations (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default public.current_workspace_id() references public.workspaces(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  poll_ids bigint[] not null check (array_length(poll_ids, 1) between 1 and 30),
  frequency text not null check (frequency in ('daily', 'weekly')),
  starts_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_poll_rotations_workspace_id on public.poll_rotations (workspace_id);

alter table public.poll_rotations enable row level security;

drop policy if exists "managers can manage poll rotations" on public.poll_rotations;
create policy "managers can manage poll rotations" on public.poll_rotations
for all to authenticated using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_manager(workspace_id));

alter table public.qr_campaigns
  add column if not exists rotation_id bigint references public.poll_rotations(id) on delete set null;

create or replace function public.get_rotation_current_poll(target_rotation_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  rotation record;
  elapsed_units integer;
  slot_index integer;
begin
  select * into rotation from public.poll_rotations where id = target_rotation_id;
  if rotation.id is null then return null; end if;

  if rotation.frequency = 'daily' then
    elapsed_units := floor(extract(epoch from (now() - rotation.starts_at)) / 86400)::integer;
  else
    elapsed_units := floor(extract(epoch from (now() - rotation.starts_at)) / (7 * 86400))::integer;
  end if;

  if elapsed_units < 0 then elapsed_units := 0; end if;
  slot_index := (elapsed_units % array_length(rotation.poll_ids, 1)) + 1;
  return rotation.poll_ids[slot_index];
end;
$$;

grant execute on function public.get_rotation_current_poll(bigint) to anon, authenticated;

-- Rotation-aware version: resolves the campaign's live poll from its rotation schedule when one is set.
drop function if exists public.get_public_qr_campaign(text);

create function public.get_public_qr_campaign(target_token text)
returns table(
  campaign_id bigint,
  poll_id bigint,
  portal_title text,
  portal_message text,
  portal_button_label text
)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  campaign record;
  resolved_poll_id bigint;
begin
  select * into campaign from public.qr_campaigns where token = target_token and is_active limit 1;
  if campaign.id is null then return; end if;

  if campaign.rotation_id is not null then
    resolved_poll_id := public.get_rotation_current_poll(campaign.rotation_id);
  else
    resolved_poll_id := campaign.poll_id;
  end if;

  if resolved_poll_id is null then return; end if;

  return query select campaign.id, resolved_poll_id, campaign.portal_title, campaign.portal_message, campaign.portal_button_label;
end;
$$;

grant execute on function public.get_public_qr_campaign(text) to anon, authenticated;
