-- iVote private organizer messages and admin product feedback.
-- Prerequisite: the secure workspace migration has been run.

create table if not exists public.organizer_messages (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  poll_id bigint not null references public.polls(id) on delete cascade,
  campaign_id bigint references public.qr_campaigns(id) on delete set null,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  reply_email text check (reply_email is null or (char_length(reply_email) <= 320 and reply_email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')),
  created_at timestamptz not null default now()
);

create table if not exists public.product_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete set null,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists idx_organizer_messages_workspace_created
on public.organizer_messages (workspace_id, created_at desc);

alter table public.organizer_messages enable row level security;
alter table public.product_feedback enable row level security;

create policy "workspace managers can view organizer messages"
on public.organizer_messages
for select to authenticated
using (public.is_workspace_manager(workspace_id));

create policy "admins can submit their own product feedback"
on public.product_feedback
for insert to authenticated
with check (user_id = auth.uid());

create or replace function public.send_organizer_message(
  target_poll_id bigint,
  target_campaign_id bigint,
  message_text text,
  contact_email text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_workspace_id uuid;
  normalized_message text := trim(message_text);
  normalized_email text := nullif(lower(trim(coalesce(contact_email, ''))), '');
begin
  if char_length(normalized_message) not between 1 and 2000 then
    raise exception 'A message between 1 and 2000 characters is required.';
  end if;
  if normalized_email is not null and normalized_email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Enter a valid reply email or leave it blank.';
  end if;

  select workspace_id into target_workspace_id from public.polls where id = target_poll_id;
  if target_workspace_id is null then raise exception 'The poll does not exist.'; end if;
  if target_campaign_id is not null and not exists (
    select 1 from public.qr_campaigns
    where id = target_campaign_id and poll_id = target_poll_id and is_active
  ) then
    raise exception 'The QR campaign is not active for this poll.';
  end if;

  insert into public.organizer_messages (workspace_id, poll_id, campaign_id, message, reply_email)
  values (target_workspace_id, target_poll_id, target_campaign_id, normalized_message, normalized_email);
end;
$$;

grant execute on function public.send_organizer_message(bigint, bigint, text, text) to anon, authenticated;