-- iVote ROI roadmap: campaign attribution, QR scans, and consented follow-up.
-- Prerequisite: run 20260907_secure_workspaces.sql first.
-- This migration is additive and preserves public anonymous vote submission.

create table if not exists public.qr_campaigns (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default public.current_workspace_id() references public.workspaces(id) on delete cascade,
  poll_id bigint references public.polls(id) on delete set null,
  name text not null check (char_length(trim(name)) between 1 and 120),
  token text not null unique check (token ~ '^[A-Za-z0-9_-]{4,120}$'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.qr_scan_events (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.qr_campaigns(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.voter_leads (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  poll_id bigint not null references public.polls(id) on delete cascade,
  campaign_id bigint references public.qr_campaigns(id) on delete set null,
  email text not null check (char_length(email) <= 320 and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (poll_id, email)
);

alter table public.votes add column if not exists campaign_id bigint references public.qr_campaigns(id) on delete set null;

create index if not exists idx_qr_campaigns_workspace_id on public.qr_campaigns (workspace_id);
create index if not exists idx_qr_campaigns_poll_id on public.qr_campaigns (poll_id);
create index if not exists idx_qr_scan_events_campaign_id on public.qr_scan_events (campaign_id);
create index if not exists idx_voter_leads_workspace_id on public.voter_leads (workspace_id);
create index if not exists idx_votes_campaign_id on public.votes (campaign_id);

-- A vote can only claim an active campaign that currently points to that poll.
create or replace function public.assign_vote_workspace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select workspace_id into new.workspace_id from public.polls where id = new.poll_id;
  if new.workspace_id is null then
    raise exception 'The poll does not exist.';
  end if;
  if new.campaign_id is not null and not exists (
    select 1 from public.qr_campaigns
    where id = new.campaign_id and poll_id = new.poll_id and is_active
  ) then
    raise exception 'The QR campaign is not active for this poll.';
  end if;
  return new;
end;
$$;

alter table public.qr_campaigns enable row level security;
alter table public.qr_scan_events enable row level security;
alter table public.voter_leads enable row level security;

drop policy if exists "members can view workspace QR campaigns" on public.qr_campaigns;
drop policy if exists "managers can manage workspace QR campaigns" on public.qr_campaigns;
drop policy if exists "members can view workspace QR scans" on public.qr_scan_events;
drop policy if exists "managers can manage consented workspace leads" on public.voter_leads;

create policy "members can view workspace QR campaigns" on public.qr_campaigns
for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "managers can manage workspace QR campaigns" on public.qr_campaigns
for all to authenticated using (public.is_workspace_manager(workspace_id))
with check (public.is_workspace_manager(workspace_id));

create policy "members can view workspace QR scans" on public.qr_scan_events
for select to authenticated
using (exists (
  select 1 from public.qr_campaigns campaign
  where campaign.id = campaign_id and public.is_workspace_member(campaign.workspace_id)
));

create policy "members can manage consented workspace leads" on public.voter_leads
for all to authenticated
using (public.is_workspace_manager(workspace_id))
with check (public.is_workspace_manager(workspace_id));

-- Public functions intentionally return only routing and aggregate-safe identifiers.
create or replace function public.get_public_qr_campaign(target_token text)
returns table(campaign_id bigint, poll_id bigint)
language sql
security definer
set search_path = public
stable
as $$
  select id, poll_id from public.qr_campaigns
  where token = target_token and is_active and poll_id is not null
  limit 1;
$$;

create or replace function public.record_qr_scan(target_campaign_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (select 1 from public.qr_campaigns where id = target_campaign_id and is_active) then
    insert into public.qr_scan_events (campaign_id) values (target_campaign_id);
  end if;
end;
$$;

create or replace function public.capture_voter_lead(
  target_poll_id bigint,
  target_campaign_id bigint,
  contact_email text,
  has_consented boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_workspace_id uuid;
  normalized_email text := lower(trim(contact_email));
begin
  if not has_consented or normalized_email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Explicit consent and a valid email are required.';
  end if;
  select workspace_id into target_workspace_id from public.polls where id = target_poll_id;
  if target_workspace_id is null then raise exception 'The poll does not exist.'; end if;
  if target_campaign_id is not null and not exists (
    select 1 from public.qr_campaigns where id = target_campaign_id and poll_id = target_poll_id and is_active
  ) then raise exception 'The QR campaign is not active for this poll.'; end if;
  insert into public.voter_leads (workspace_id, poll_id, campaign_id, email)
  values (target_workspace_id, target_poll_id, target_campaign_id, normalized_email)
  on conflict (poll_id, email) do nothing;
end;
$$;

grant execute on function public.get_public_qr_campaign(text) to anon, authenticated;
grant execute on function public.record_qr_scan(bigint) to anon, authenticated;
grant execute on function public.capture_voter_lead(bigint, bigint, text, boolean) to anon, authenticated;