-- Lets a single QR code fan out to multiple things at once: any mix of extra
-- polls and admin-authored "info" cards (an announcement, a menu link, house
-- rules, whatever the venue wants to share). Fully backward compatible: a QR
-- campaign with zero rows here behaves exactly as before (its single poll_id,
-- or its rotation, resolves immediately). As soon as a campaign has one or
-- more rows here, QrRedirect shows a menu of everything listed instead.
--
-- Note: the ordering column is named "sort_order", not "position" - "position"
-- is a reserved SQL keyword (used by the POSITION(substring IN string)
-- function) and cannot be used as a bare identifier without quoting it
-- everywhere, so this migration avoids it entirely.
create table if not exists public.qr_campaign_items (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.qr_campaigns(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  item_type text not null check (item_type in ('poll', 'info')),
  poll_id bigint references public.polls(id) on delete cascade,
  title text check (title is null or char_length(trim(title)) <= 120),
  body text check (body is null or char_length(trim(body)) <= 2000),
  link_url text check (link_url is null or char_length(link_url) <= 500),
  link_label text check (link_label is null or char_length(link_label) <= 60),
  sort_order int,
  created_at timestamptz not null default now(),
  constraint qr_campaign_items_shape check (
    (item_type = 'poll' and poll_id is not null and title is null and body is null and link_url is null and link_label is null)
    or
    (item_type = 'info' and poll_id is null and title is not null and char_length(trim(title)) > 0)
  )
);

create index if not exists idx_qr_campaign_items_campaign on public.qr_campaign_items (campaign_id, sort_order);
create index if not exists idx_qr_campaign_items_workspace on public.qr_campaign_items (workspace_id);

alter table public.qr_campaign_items enable row level security;

drop policy if exists "members can view workspace qr items" on public.qr_campaign_items;
drop policy if exists "managers can manage workspace qr items" on public.qr_campaign_items;

create policy "members can view workspace qr items" on public.qr_campaign_items
for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "managers can manage workspace qr items" on public.qr_campaign_items
for all to authenticated using (public.is_workspace_manager(workspace_id))
with check (public.is_workspace_manager(workspace_id));

-- Derives workspace_id from the parent campaign (so the client never has to
-- guess it), confirms a poll item belongs to that same workspace, appends new
-- items to the end of the list by default, and caps the list at 20 items so a
-- single QR code can't be turned into an unbounded menu.
create or replace function public.qr_campaign_items_before_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  campaign_workspace_id uuid;
  poll_workspace_id uuid;
  existing_count int;
begin
  select workspace_id into campaign_workspace_id from public.qr_campaigns where id = new.campaign_id;
  if campaign_workspace_id is null then
    raise exception 'The QR campaign does not exist.';
  end if;
  new.workspace_id := campaign_workspace_id;

  if new.item_type = 'poll' then
    select workspace_id into poll_workspace_id from public.polls where id = new.poll_id;
    if poll_workspace_id is null or poll_workspace_id <> campaign_workspace_id then
      raise exception 'The poll must belong to the same workspace as the QR campaign.';
    end if;
  end if;

  if tg_op = 'INSERT' then
    select count(*) into existing_count from public.qr_campaign_items where campaign_id = new.campaign_id;
    if existing_count >= 20 then
      raise exception 'A QR code can have at most 20 items. Remove one before adding another.';
    end if;
    if new.sort_order is null then
      select coalesce(max(sort_order), -1) + 1 into new.sort_order
      from public.qr_campaign_items where campaign_id = new.campaign_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_qr_campaign_items_before_write on public.qr_campaign_items;
create trigger trg_qr_campaign_items_before_write
before insert or update on public.qr_campaign_items
for each row execute function public.qr_campaign_items_before_write();

-- Public, read-only lookup for the voter-facing QR scan flow: every item
-- attached to an active campaign, in display order, with poll branding
-- included so the "menu" screen can style itself consistently with the poll
-- the venue already branded.
drop function if exists public.get_public_qr_campaign_items(text);

create function public.get_public_qr_campaign_items(target_token text)
returns table(
  item_id bigint,
  campaign_id bigint,
  portal_title text,
  portal_message text,
  item_type text,
  sort_order int,
  poll_id bigint,
  poll_question text,
  poll_brand_name text,
  poll_brand_logo_url text,
  poll_brand_primary_color text,
  poll_brand_accent_color text,
  title text,
  body text,
  link_url text,
  link_label text
)
language sql
security definer
set search_path = public
stable
as $$
  select
    i.id,
    c.id,
    c.portal_title,
    c.portal_message,
    i.item_type,
    i.sort_order,
    i.poll_id,
    p.question,
    p.brand_name,
    p.brand_logo_url,
    p.brand_primary_color,
    p.brand_accent_color,
    i.title,
    i.body,
    i.link_url,
    i.link_label
  from public.qr_campaign_items i
  join public.qr_campaigns c on c.id = i.campaign_id
  left join public.polls p on p.id = i.poll_id
  where c.token = target_token and c.is_active
  order by i.sort_order asc nulls last, i.id asc;
$$;

grant execute on function public.get_public_qr_campaign_items(text) to anon, authenticated;
