-- iVote launch foundation. Prerequisites: 20260907_secure_workspaces.sql and
-- 20260907_roi_roadmap.sql have been run. This migration is additive.

create table if not exists public.workspace_subscriptions (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'starter', 'growth')),
  status text not null default 'active' check (status in ('active', 'trialing', 'past_due', 'canceled', 'inactive', 'incomplete', 'unpaid', 'paused')),
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.privacy_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete set null,
  request_type text not null check (request_type in ('account_deletion', 'consent_withdrawal', 'data_export')),
  status text not null default 'requested' check (status in ('requested', 'in_review', 'completed', 'rejected')),
  details text check (char_length(details) <= 2000),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.user_answers add column if not exists is_hidden boolean not null default false;

create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  poll_id bigint not null references public.polls(id) on delete cascade,
  reported_answer text not null check (char_length(trim(reported_answer)) between 1 and 1000),
  reason text not null check (reason in ('offensive', 'personal_data', 'spam', 'other')),
  status text not null default 'open' check (status in ('open', 'reviewed', 'hidden', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create index if not exists idx_privacy_requests_user_id on public.privacy_requests(user_id, created_at desc);
create index if not exists idx_content_reports_workspace_status on public.content_reports(workspace_id, status, created_at desc);

alter table public.workspace_subscriptions enable row level security;
alter table public.privacy_requests enable row level security;
alter table public.content_reports enable row level security;

drop policy if exists "members can view workspace subscriptions" on public.workspace_subscriptions;
create policy "members can view workspace subscriptions" on public.workspace_subscriptions
for select to authenticated using (public.is_workspace_member(workspace_id));

drop policy if exists "users can view own privacy requests" on public.privacy_requests;
drop policy if exists "users can create own privacy requests" on public.privacy_requests;
create policy "users can view own privacy requests" on public.privacy_requests
for select to authenticated using (user_id = auth.uid());
create policy "users can create own privacy requests" on public.privacy_requests
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "managers can view content reports" on public.content_reports;
drop policy if exists "managers can review content reports" on public.content_reports;
create policy "managers can view content reports" on public.content_reports
for select to authenticated using (public.is_workspace_manager(workspace_id));
create policy "managers can review content reports" on public.content_reports
for update to authenticated using (public.is_workspace_manager(workspace_id))
with check (public.is_workspace_manager(workspace_id));

create or replace function public.workspace_plan(target_workspace_id uuid)
returns text language sql security definer set search_path = public stable as $$
  select coalesce((select plan from public.workspace_subscriptions
    where workspace_id = target_workspace_id and status in ('active', 'trialing')), 'free');
$$;

create or replace function public.workspace_plan_limits(target_workspace_id uuid default public.current_workspace_id())
returns table(plan text, poll_limit integer, campaign_limit integer)
language sql security definer set search_path = public stable as $$
  select public.workspace_plan(target_workspace_id),
    case public.workspace_plan(target_workspace_id) when 'starter' then 25 when 'growth' then 250 else 3 end,
    case public.workspace_plan(target_workspace_id) when 'starter' then 10 when 'growth' then 100 else 0 end;
$$;

create or replace function public.enforce_workspace_poll_limit()
returns trigger language plpgsql security definer set search_path = public as $$
declare allowed_polls integer;
begin
  select poll_limit into allowed_polls from public.workspace_plan_limits(new.workspace_id);
  if (select count(*) from public.polls where workspace_id = new.workspace_id) >= allowed_polls then
    raise exception 'Your workspace has reached its poll limit. Choose a higher plan to create more polls.';
  end if;
  return new;
end;
$$;

drop trigger if exists polls_enforce_workspace_plan_limit on public.polls;
create trigger polls_enforce_workspace_plan_limit
before insert on public.polls for each row execute procedure public.enforce_workspace_poll_limit();

create or replace function public.enforce_workspace_campaign_limit()
returns trigger language plpgsql security definer set search_path = public as $$
declare allowed_campaigns integer;
begin
  select campaign_limit into allowed_campaigns from public.workspace_plan_limits(new.workspace_id);
  if (select count(*) from public.qr_campaigns where workspace_id = new.workspace_id) >= allowed_campaigns then
    raise exception 'Your workspace has reached its QR campaign limit. Choose a higher plan to create more campaigns.';
  end if;
  return new;
end;
$$;

drop trigger if exists qr_campaigns_enforce_workspace_plan_limit on public.qr_campaigns;
create trigger qr_campaigns_enforce_workspace_plan_limit
before insert on public.qr_campaigns for each row execute procedure public.enforce_workspace_campaign_limit();

create or replace function public.report_public_user_answer(target_poll_id bigint, target_answer text, report_reason text)
returns void language plpgsql security definer set search_path = public as $$
declare target_workspace_id uuid;
begin
  if report_reason not in ('offensive', 'personal_data', 'spam', 'other') then raise exception 'Invalid report reason.'; end if;
  select workspace_id into target_workspace_id from public.polls where id = target_poll_id;
  if target_workspace_id is null or not exists (
    select 1 from public.user_answers where poll_id = target_poll_id and answer = trim(target_answer) and not is_hidden
  ) then raise exception 'The answer cannot be reported.'; end if;
  insert into public.content_reports (workspace_id, poll_id, reported_answer, reason)
  values (target_workspace_id, target_poll_id, trim(target_answer), report_reason);
end;
$$;

grant execute on function public.workspace_plan_limits(uuid) to authenticated;
grant execute on function public.report_public_user_answer(bigint, text, text) to anon, authenticated;