-- iVote workspace tenancy and ownership migration.
-- Run this entire file in the Supabase SQL Editor before deploying the matching app code.

create extension if not exists pgcrypto;

create table if not exists public.workspace_members (
  id bigint generated by default as identity primary key,
  user_id uuid,
  name text not null,
  email text,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.qr_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  token text not null,
  current_poll_id bigint references public.polls(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'My workspace',
  logo_url text,
  primary_color text not null default '#2563eb',
  accent_color text not null default '#0f172a',
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.workspace_members add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.qr_locations add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.polls add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.votes add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;

-- One legacy workspace per poll creator preserves existing polls during migration.
insert into public.workspaces (name, owner_id)
select 'My workspace', poll.creator_id
from public.polls poll
where poll.creator_id is not null
  and not exists (select 1 from public.workspaces workspace where workspace.owner_id = poll.creator_id)
group by poll.creator_id;

update public.polls poll
set workspace_id = workspace.id
from public.workspaces workspace
where poll.workspace_id is null and workspace.owner_id = poll.creator_id;

insert into public.workspace_members (workspace_id, user_id, name, email, role)
select workspace.id, workspace.owner_id, 'Workspace Owner', coalesce(user_record.email, ''), 'owner'
from public.workspaces workspace
left join auth.users user_record on user_record.id = workspace.owner_id
where not exists (
  select 1 from public.workspace_members member
  where member.workspace_id = workspace.id and member.user_id = workspace.owner_id
);

update public.workspace_members member
set workspace_id = workspace.id
from public.workspaces workspace
where member.workspace_id is null and member.user_id = workspace.owner_id;

update public.qr_locations location
set workspace_id = poll.workspace_id
from public.polls poll
where location.workspace_id is null and location.current_poll_id = poll.id;

update public.votes vote
set workspace_id = poll.workspace_id
from public.polls poll
where vote.workspace_id is null and vote.poll_id = poll.id;

create or replace function public.is_workspace_member(target_workspace_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = target_workspace_id and user_id = auth.uid()
  );
$$;

create or replace function public.is_workspace_manager(target_workspace_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
      and role in ('owner', 'editor')
  );
$$;

create or replace function public.ensure_my_workspace()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_workspace_id uuid;
  claimed_workspace_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.';
  end if;

  select workspace_id into existing_workspace_id
  from public.workspace_members
  where user_id = auth.uid()
  order by created_at
  limit 1;

  if existing_workspace_id is not null then
    return existing_workspace_id;
  end if;

  update public.workspace_members
  set user_id = auth.uid()
  where id = (
    select id from public.workspace_members
    where user_id is null and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    order by created_at
    limit 1
  )
  returning workspace_id into claimed_workspace_id;

  if claimed_workspace_id is not null then
    return claimed_workspace_id;
  end if;

  insert into public.workspaces (name, owner_id)
  values ('My workspace', auth.uid())
  returning id into existing_workspace_id;

  insert into public.workspace_members (workspace_id, user_id, name, email, role)
  values (existing_workspace_id, auth.uid(), 'Workspace Owner', coalesce(auth.jwt() ->> 'email', ''), 'owner');

  return existing_workspace_id;
end;
$$;

create or replace function public.current_workspace_id()
returns uuid
language sql
security definer
set search_path = public
as $$ select public.ensure_my_workspace(); $$;

create or replace function public.assign_vote_workspace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select workspace_id into new.workspace_id from public.polls where id = new.poll_id;
  return new;
end;
$$;

drop trigger if exists votes_assign_workspace on public.votes;
create trigger votes_assign_workspace
before insert on public.votes
for each row execute procedure public.assign_vote_workspace();

alter table public.polls alter column workspace_id set default public.current_workspace_id();
alter table public.qr_locations alter column workspace_id set default public.current_workspace_id();

create index if not exists idx_polls_workspace_id on public.polls (workspace_id);
create index if not exists idx_votes_workspace_id on public.votes (workspace_id);
create index if not exists idx_qr_locations_workspace_id on public.qr_locations (workspace_id);
create index if not exists idx_workspace_members_workspace_user on public.workspace_members (workspace_id, user_id);

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.qr_locations enable row level security;
alter table public.polls enable row level security;
alter table public.votes enable row level security;

do $$
declare policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname from pg_policies
    where schemaname = 'public' and tablename in ('workspaces', 'workspace_members', 'qr_locations', 'polls', 'votes')
  loop
    execute format('drop policy if exists %I on %I.%I', policy_record.policyname, policy_record.schemaname, policy_record.tablename);
  end loop;
end;
$$;

create policy "workspace members can view their workspace" on public.workspaces
for select to authenticated using (public.is_workspace_member(id));
create policy "workspace owners can update their workspace" on public.workspaces
for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create policy "members can view their workspace team" on public.workspace_members
for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "managers can add workspace team members" on public.workspace_members
for insert to authenticated with check (public.is_workspace_manager(workspace_id));
create policy "owners can remove workspace team members" on public.workspace_members
for delete to authenticated using (public.is_workspace_manager(workspace_id) and role <> 'owner');

create policy "members can manage workspace QR locations" on public.qr_locations
for all to authenticated using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_manager(workspace_id));
create policy "members can manage workspace polls" on public.polls
for all to authenticated using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_manager(workspace_id));
create policy "members can view workspace votes" on public.votes
for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "anyone can submit a vote for a workspace poll" on public.votes
for insert to anon, authenticated with check (workspace_id is not null);

-- Existing public voting and QR redirects keep working through narrowly scoped functions.
create or replace function public.get_public_poll(target_poll_id bigint)
returns setof public.polls
language sql
security definer
set search_path = public
stable
as $$ select * from public.polls where id = target_poll_id; $$;

create or replace function public.get_public_poll_by_qr(target_url text)
returns table(id bigint)
language sql
security definer
set search_path = public
stable
as $$ select poll.id from public.polls poll where poll.stable_short_url = target_url; $$;

create or replace function public.get_public_poll_votes(target_poll_id bigint)
returns table(answer text, created_at timestamptz)
language sql
security definer
set search_path = public
stable
as $$ select vote.answer, vote.created_at from public.votes vote where vote.poll_id = target_poll_id; $$;

grant execute on function public.ensure_my_workspace() to authenticated;
grant execute on function public.get_public_poll(bigint) to anon, authenticated;
grant execute on function public.get_public_poll_by_qr(text) to anon, authenticated;
grant execute on function public.get_public_poll_votes(bigint) to anon, authenticated;