-- ROI reporting, per-location comparison, and staff/table attribution.
-- Run after 20260909_loyalty_and_reputation.sql.

-- ROI report: the admin sets an estimated dollar value per outcome once,
-- and the dashboard turns tracked activity into one estimated value.
create table if not exists public.roi_settings (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  reward_value numeric not null default 5,
  review_value numeric not null default 10,
  repeat_visit_value numeric not null default 8,
  updated_at timestamptz not null default now()
);

alter table public.roi_settings enable row level security;

drop policy if exists "managers can view their roi settings" on public.roi_settings;
drop policy if exists "managers can manage their roi settings" on public.roi_settings;
create policy "managers can view their roi settings" on public.roi_settings
for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "managers can manage their roi settings" on public.roi_settings
for all to authenticated using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_manager(workspace_id));

-- A timestamped log of reward redemptions, so the ROI report can count
-- "this month" activity instead of only an all-time running total.
create table if not exists public.reward_redemption_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  poll_id bigint not null references public.polls(id) on delete cascade,
  redeemed_at timestamptz not null default now()
);

create index if not exists idx_reward_redemption_events_workspace on public.reward_redemption_events (workspace_id, redeemed_at desc);

alter table public.reward_redemption_events enable row level security;

drop policy if exists "managers can view reward redemption events" on public.reward_redemption_events;
create policy "managers can view reward redemption events" on public.reward_redemption_events
for select to authenticated using (public.is_workspace_manager(workspace_id));

create or replace function public.redeem_reward_code(target_code text)
returns table(poll_id bigint, question text, reward_redeemed_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  matched_poll_id bigint;
  matched_workspace_id uuid;
begin
  select id, polls.workspace_id into matched_poll_id, matched_workspace_id
  from public.polls
  where reward_code = target_code and workspace_id = public.current_workspace_id();

  if matched_poll_id is null then
    raise exception 'No poll in your workspace has that reward code.';
  end if;

  update public.polls set reward_redeemed_count = reward_redeemed_count + 1
  where id = matched_poll_id;

  insert into public.reward_redemption_events (workspace_id, poll_id)
  values (matched_workspace_id, matched_poll_id);

  return query select id, polls.question, polls.reward_redeemed_count from public.polls where id = matched_poll_id;
end;
$$;

grant execute on function public.redeem_reward_code(text) to authenticated;

-- Staff/table attribution: whoever is assigned to a QR campaign right now is
-- attached to any vote that comes in through it, decided server-side so a
-- voter can never spoof who they were served by.
alter table public.qr_campaigns
  add column if not exists assigned_staff_name text;

alter table public.votes
  add column if not exists staff_name text;

create or replace function public.assign_vote_workspace()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select workspace_id into new.workspace_id from public.polls where id = new.poll_id;
  if new.workspace_id is null then
    raise exception 'The poll does not exist.';
  end if;
  if new.campaign_id is not null and not exists (
    select 1 from public.qr_campaigns
    where id = new.campaign_id and poll_id = new.poll_id and is_active
  ) then
    raise exception 'The QR campaign is not active for this poll.';
  end if;

  new.staff_name := null;
  if new.campaign_id is not null then
    select assigned_staff_name into new.staff_name
    from public.qr_campaigns
    where id = new.campaign_id;
  end if;

  return new;
end;
$$;
