-- Public trust score for the embeddable badge widget (best-to-worst answer order assumed).
create or replace function public.get_public_poll_trust_score(target_poll_id bigint)
returns table(score numeric, total_votes integer)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  answer_list text[];
  answer_count integer;
begin
  select answers into answer_list from public.polls where id = target_poll_id;
  answer_count := coalesce(array_length(answer_list, 1), 0);

  if answer_count <= 1 then
    return query select 100::numeric, (select count(*)::integer from public.votes where poll_id = target_poll_id);
    return;
  end if;

  return query
  select
    coalesce(avg((1 - (array_position(answer_list, v.answer) - 1)::numeric / (answer_count - 1))) * 100, 0),
    count(*)::integer
  from public.votes v
  where v.poll_id = target_poll_id and v.answer = any(answer_list);
end;
$$;

grant execute on function public.get_public_poll_trust_score(bigint) to anon, authenticated;

-- Closed-loop public updates ("We heard you") a workspace can post per poll or workspace-wide.
create table if not exists public.workspace_updates (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  poll_id bigint references public.polls(id) on delete set null,
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists idx_workspace_updates_workspace_id on public.workspace_updates (workspace_id);
create index if not exists idx_workspace_updates_poll_id on public.workspace_updates (poll_id);

alter table public.workspace_updates enable row level security;

drop policy if exists "managers can manage workspace updates" on public.workspace_updates;
create policy "managers can manage workspace updates" on public.workspace_updates
for all to authenticated using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_manager(workspace_id));

create or replace function public.get_public_workspace_updates(target_poll_id bigint)
returns table(id bigint, message text, created_at timestamptz)
language sql
security definer
set search_path = public
stable
as $$
  select u.id, u.message, u.created_at
  from public.workspace_updates u
  join public.polls p on p.id = target_poll_id
  where u.workspace_id = p.workspace_id and (u.poll_id = target_poll_id or u.poll_id is null)
  order by u.created_at desc
  limit 10;
$$;

grant execute on function public.get_public_workspace_updates(bigint) to anon, authenticated;
