-- Churn/usage instrumentation (see TODO.md "Product" section): the dashboard showed raw vote
-- counts, but nothing tracked whether a workspace owner was actually *using* the product -
-- logging into /admin, opening results, switching tabs. This adds the minimum needed to answer
-- that before making pricing/retention decisions, without building a whole internal "God mode"
-- admin panel: a couple of columns/tables plus one convenience view meant to be queried
-- directly from the Supabase SQL/Table editor (it is intentionally not exposed to the anon/
-- authenticated REST API - only the operator running SQL as themselves can see it).

alter table public.workspaces add column if not exists last_active_at timestamptz;

-- Bump last_active_at on every dashboard load. ensure_my_workspace() already runs on every
-- /admin visit (it's the first thing loadWorkspaceProfile() calls), so this is the cheapest,
-- always-correct place to record "this workspace was opened" without a separate API call.
create or replace function public.ensure_my_workspace()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_workspace_id uuid;
  claimed_workspace_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.';
  end if;

  select workspace_id into existing_workspace_id
  from public.workspace_members
  where user_id = auth.uid()
  order by created_at
  limit 1;

  if existing_workspace_id is not null then
    update public.workspaces set last_active_at = now() where id = existing_workspace_id;
    return existing_workspace_id;
  end if;

  update public.workspace_members
  set user_id = auth.uid()
  where id = (
    select id from public.workspace_members
    where user_id is null and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    order by created_at
    limit 1
  )
  returning workspace_id into claimed_workspace_id;

  if claimed_workspace_id is not null then
    update public.workspaces set last_active_at = now() where id = claimed_workspace_id;
    return claimed_workspace_id;
  end if;

  insert into public.workspaces (name, owner_id, last_active_at)
  values ('My workspace', auth.uid(), now())
  returning id into existing_workspace_id;

  insert into public.workspace_members (workspace_id, user_id, name, email, role)
  values (existing_workspace_id, auth.uid(), 'Workspace Owner', coalesce(auth.jwt() ->> 'email', ''), 'owner');

  return existing_workspace_id;
end;
$$;

-- Lightweight event log for "which admin tabs/features get opened at all" - just enough to
-- prioritize future work by real usage instead of guesswork, without full analytics tooling.
create table if not exists public.workspace_admin_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('tab_open')),
  tab text,
  created_at timestamptz not null default now()
);

create index if not exists idx_workspace_admin_events_workspace_created
  on public.workspace_admin_events(workspace_id, created_at desc);

alter table public.workspace_admin_events enable row level security;

drop policy if exists "managers can view workspace admin events" on public.workspace_admin_events;
create policy "managers can view workspace admin events" on public.workspace_admin_events
for select to authenticated using (public.is_workspace_manager(workspace_id));

-- No insert policy is needed: the client never writes to this table directly, only through
-- log_workspace_admin_event() below, which resolves the caller's own workspace server-side.
create or replace function public.log_workspace_admin_event(p_event_type text, p_tab text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare target_workspace_id uuid;
begin
  if p_event_type not in ('tab_open') then
    return;
  end if;

  select workspace_id into target_workspace_id
  from public.workspace_members
  where user_id = auth.uid()
  order by created_at
  limit 1;

  if target_workspace_id is null then
    return;
  end if;

  insert into public.workspace_admin_events (workspace_id, user_id, event_type, tab)
  values (target_workspace_id, auth.uid(), p_event_type, p_tab);
end;
$$;

grant execute on function public.log_workspace_admin_event(text, text) to authenticated;

-- Convenience view for you (the operator) to query directly in the Supabase SQL/Table editor -
-- deliberately not granted to anon/authenticated, so it never becomes visible through the app.
create or replace view public.workspace_engagement_summary as
select
  w.id as workspace_id,
  w.name,
  w.last_active_at,
  (w.last_active_at is not null and w.last_active_at > now() - interval '7 days') as active_last_7_days,
  (
    select count(distinct e.tab) from public.workspace_admin_events e
    where e.workspace_id = w.id and e.created_at > now() - interval '30 days'
  ) as distinct_tabs_opened_30d,
  (
    select count(*) from public.workspace_admin_events e
    where e.workspace_id = w.id and e.created_at > now() - interval '30 days'
  ) as admin_events_30d
from public.workspaces w;
