-- Repeat-visit recognition (opt-in only, voting itself stays anonymous) and
-- public review lever: review-claim reminders and pulled-in public reputation.
-- Run after 20260909_feedback_benefits.sql.

alter table public.workspaces
  add column if not exists google_place_id text;

-- Cross-poll visit recognition, keyed only by an email the voter chose to leave.
-- This never requires an account: a voter who never opts in never appears here.
create table if not exists public.voter_profiles (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text not null check (char_length(email) <= 320),
  visit_count int not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  winback_sent_at timestamptz,
  unique (workspace_id, email)
);

create index if not exists idx_voter_profiles_workspace on public.voter_profiles (workspace_id);

alter table public.voter_profiles enable row level security;

drop policy if exists "managers can view voter profiles" on public.voter_profiles;
create policy "managers can view voter profiles" on public.voter_profiles
for select to authenticated using (public.is_workspace_manager(workspace_id));

-- Optional per-poll bonus shown only once a returning voter crosses the visit threshold.
alter table public.polls
  add column if not exists loyalty_visit_threshold int,
  add column if not exists loyalty_benefit_message text,
  add column if not exists loyalty_benefit_code text,
  add column if not exists loyalty_benefit_url text;

-- capture_voter_lead now also tracks cross-poll visit recognition and reports the
-- voter's current visit count back to the caller so the app can show a loyalty bonus.
drop function if exists public.capture_voter_lead(bigint, bigint, text, boolean);

create or replace function public.capture_voter_lead(
  target_poll_id bigint,
  target_campaign_id bigint,
  contact_email text,
  has_consented boolean
)
returns table(id bigint, visit_count int)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_workspace_id uuid;
  normalized_email text := lower(trim(contact_email));
  new_lead_id bigint;
  next_visit_count int;
begin
  if not has_consented or normalized_email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Explicit consent and a valid email are required.';
  end if;

  select workspace_id into target_workspace_id from public.polls where id = target_poll_id;
  if target_workspace_id is null then raise exception 'The poll does not exist.'; end if;

  if target_campaign_id is not null and not exists (
    select 1 from public.qr_campaigns where id = target_campaign_id and poll_id = target_poll_id and is_active
  ) then raise exception 'The QR campaign is not active for this poll.'; end if;

  insert into public.voter_leads (workspace_id, poll_id, campaign_id, email)
  values (target_workspace_id, target_poll_id, target_campaign_id, normalized_email)
  on conflict (poll_id, email) do update set email = excluded.email
  returning voter_leads.id into new_lead_id;

  insert into public.voter_profiles (workspace_id, email, visit_count, first_seen_at, last_seen_at)
  values (target_workspace_id, normalized_email, 1, now(), now())
  on conflict (workspace_id, email) do update
    set visit_count = voter_profiles.visit_count + 1,
        last_seen_at = now(),
        winback_sent_at = null
  returning voter_profiles.visit_count into next_visit_count;

  return query select new_lead_id, next_visit_count;
end;
$$;

grant execute on function public.capture_voter_lead(bigint, bigint, text, boolean) to anon, authenticated;

-- Win-back email settings, parallel to lead_nurture_settings.
create table if not exists public.winback_settings (
  workspace_id uuid primary key references public.workspaces(id) on delete cascade,
  is_enabled boolean not null default false,
  days_since_last_visit int not null default 30 check (days_since_last_visit between 7 and 365),
  subject text,
  message text,
  updated_at timestamptz not null default now()
);

alter table public.winback_settings enable row level security;

drop policy if exists "managers can view their winback settings" on public.winback_settings;
drop policy if exists "managers can manage their winback settings" on public.winback_settings;
create policy "managers can view their winback settings" on public.winback_settings
for select to authenticated using (public.is_workspace_member(workspace_id));
create policy "managers can manage their winback settings" on public.winback_settings
for all to authenticated using (public.is_workspace_member(workspace_id)) with check (public.is_workspace_manager(workspace_id));

-- Public review lever: let a voter optionally leave the same opt-in email so the
-- workspace can send a single reminder if they never followed up on a claim.
alter table public.review_benefit_claims
  add column if not exists contact_email text,
  add column if not exists reminder_sent_at timestamptz;

drop function if exists public.create_review_benefit_claim(bigint, text[]);

create or replace function public.create_review_benefit_claim(
  target_poll_id bigint,
  selected_answers text[],
  contact_email text default null
)
returns table(claim_token uuid, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_workspace_id uuid;
  target_triggers text[];
  new_token uuid;
  normalized_email text := nullif(lower(trim(coalesce(contact_email, ''))), '');
begin
  select workspace_id, review_trigger_answers
    into target_workspace_id, target_triggers
  from public.polls
  where id = target_poll_id;

  if target_workspace_id is null then
    raise exception 'The poll does not exist.';
  end if;

  if coalesce(array_length(target_triggers, 1), 0) = 0
    or not exists (
      select 1 from unnest(coalesce(selected_answers, '{}')) answer
      where answer = any(target_triggers)
    ) then
    raise exception 'This vote is not eligible for an external review benefit.';
  end if;

  if normalized_email is not null and normalized_email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    normalized_email := null;
  end if;

  insert into public.review_benefit_claims (workspace_id, poll_id, selected_answers, contact_email)
  values (target_workspace_id, target_poll_id, coalesce(selected_answers, '{}'), normalized_email)
  returning review_benefit_claims.claim_token into new_token;

  return query select new_token, 'pending'::text;
end;
$$;

grant execute on function public.create_review_benefit_claim(bigint, text[], text) to anon, authenticated;

-- Public reputation pulled in from Google (rating/review count over time).
create table if not exists public.reputation_snapshots (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  source text not null default 'google' check (source in ('google')),
  rating numeric,
  rating_count int,
  captured_at timestamptz not null default now()
);

create index if not exists idx_reputation_snapshots_workspace on public.reputation_snapshots (workspace_id, captured_at desc);

alter table public.reputation_snapshots enable row level security;

drop policy if exists "managers can view reputation snapshots" on public.reputation_snapshots;
create policy "managers can view reputation snapshots" on public.reputation_snapshots
for select to authenticated using (public.is_workspace_manager(workspace_id));
