-- Durable results for the scheduled Stripe reconciliation and privacy-request processor.
-- Both tables are service-role-only: no browser session should be able to write or read them.

create table if not exists public.stripe_reconciliation_runs (
  id bigint generated by default as identity primary key,
  ran_at timestamptz not null default now(),
  mismatch_count integer not null default 0 check (mismatch_count >= 0),
  summary jsonb not null
);

alter table public.stripe_reconciliation_runs enable row level security;

alter table public.privacy_requests
  add column if not exists processed_at timestamptz;

create index if not exists idx_privacy_requests_processing
  on public.privacy_requests(status, created_at);
