-- iVote business/schema alignment for Supabase
-- Run this in the Supabase SQL Editor if you want DB-backed QR locations and team role storage.

create table if not exists public.qr_locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  token text not null unique,
  current_poll_id bigint references public.polls(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  id bigint generated by default as identity primary key,
  user_id uuid,
  name text not null,
  email text,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create extension if not exists pgcrypto;

alter table public.polls
  add column if not exists location_name text,
  add column if not exists location_token text,
  add column if not exists starts_at timestamptz,
  add column if not exists ends_at timestamptz,
  add column if not exists closed_at timestamptz,
  add column if not exists status text default 'active',
  add column if not exists brand_name text,
  add column if not exists brand_logo_url text,
  add column if not exists brand_primary_color text,
  add column if not exists brand_accent_color text,
  add column if not exists template_key text;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists qr_locations_set_updated_at on public.qr_locations;
create trigger qr_locations_set_updated_at
before update on public.qr_locations
for each row
execute procedure public.set_updated_at();

drop trigger if exists workspace_members_set_updated_at on public.workspace_members;
create trigger workspace_members_set_updated_at
before update on public.workspace_members
for each row
execute procedure public.set_updated_at();

alter table public.qr_locations enable row level security;
alter table public.workspace_members enable row level security;

drop policy if exists "qr_locations_all_authenticated" on public.qr_locations;
create policy "qr_locations_all_authenticated"
on public.qr_locations
for all
to authenticated
using (true)
with check (true);

drop policy if exists "workspace_members_all_authenticated" on public.workspace_members;
create policy "workspace_members_all_authenticated"
on public.workspace_members
for all
to authenticated
using (true)
with check (true);

create index if not exists idx_qr_locations_name on public.qr_locations (name);
create index if not exists idx_qr_locations_token on public.qr_locations (token);
create index if not exists idx_qr_locations_current_poll on public.qr_locations (current_poll_id);
create index if not exists idx_workspace_members_user_id on public.workspace_members (user_id);
